### ISSUE TITLE
investigate empty output values from the api

### ISSUE THREAD

**Issue by zargot** [Big-Life-Lab/PHES-ODM-sharing#42]
verify the consistency of empty values being return from the api. Ex: if there are empty cells in the input excel sheet, then empty values being returned as output from the api should all have the same type, either None or empty string.

**Comment by yulric** [comment]
Also see [this comment](https://github.com/Big-Life-Lab/PHES-ODM-sharing/pull/32#discussion_r1725730293).

**Comment by zargot** [comment]
the existing tests in `test_api.py` show that all the empty values coming from the excel input file ends up as an empty string after extraction. Is that good enough or do you have a different test in mind, @yulric?

**Comment by yulric** [comment]
> the existing tests in `test_api.py` show that all the empty values coming from the excel input file ends up as an empty string after extraction. Is that good enough or do you have a different test in mind, @yulric?

That sounds good but with re my comment I was more talking about the error that was happening. If that's not the case anymore then we should be good for this issue.

**Comment by zargot** [comment]
> That sounds good but with re my comment I was more talking about the error that was happening. If that's not the case anymore then we should be good for this issue.

I'm not able to reproduce the error you referred to. Are you able to reproduce it?

**Comment by yulric** [comment]
> > That sounds good but with re my comment I was more talking about the error that was happening. If that's not the case anymore then we should be good for this issue.
> 
> I'm not able to reproduce the error you referred to. Are you able to reproduce it

Nope, looks like its fixed.
