### ISSUE TITLE
deferred: having schema name in generated output filename

### ISSUE THREAD

**Issue by zargot** [Big-Life-Lab/PHES-ODM-sharing#59]
Won't this be an issue if the user passes in two files that are for the same table? I think its better for the user if the output file name is the same as the input file to avoid confusion.

_Originally posted by @yulric in https://github.com/Big-Life-Lab/PHES-ODM-sharing/pull/57#discussion_r1775525182_

**Comment by zargot** [comment]
how can two files be for the same table? In any case, the input file name is not used since it doesn't make sense when using multiple input files. The schema is always singular, so that makes more sense I think? 

Ex: the user has the schema `labfilter.csv`, which generates the output filenames:
- `labfilter-mylab-measures.csv`
- `labfilter-mylab-samples.csv`

**Comment by yulric** [comment]
The user can for example pass in two CSV files that that contains samples for different dates, resulting in two files that are for the same table but that contain different data. If they do that then this would error right since we're creating two files with the same name. 

We may want to disallow this but good to ask Mathew/Doug.

**Comment by zargot** [comment]
> The user can for example pass in two CSV files that that contains samples for different dates, resulting in two files that are for the same table but that contain different data. If they do that then this would error right since we're creating two files with the same name.
> 
> We may want to disallow this but good to ask Mathew/Doug.

I don't think any part of the code supports that edge case. It can be a candidate for the next version?

**Comment by yulric** [comment]
Lets ask @DougManuel or @mathew-thomson. Regardless of what they say we will need to implement some code to at least acknowledge this case, for example throwing an error if we decide to not support it.

**Comment by zargot** [comment]
> Lets ask @DougManuel or @mathew-thomson. Regardless of what they say we will need to implement some code to at least acknowledge this case, for example throwing an error if we decide to not support it.

Actually, it's not currently possible to input more than one CSV file for each table since the table name comes from the filename, and any two files can't have the same name. When the format isn't CSV, then multiple files aren't allowed either. 

I added the error-message requirement to #56, which may change how this works.

**Comment by zargot** [comment]
> True but once we implement the feature where they can map a table to a CSV file this becomes an issue again?

Yes, that's why I added it to that issue (#56). Isn't that sufficient?

**Comment by yulric** [comment]
That works but would wait to see if Doug of Mathew think this needs to be supported or if an error should be raised for now.
